OZ-1052: Use aggregated report file for multi module projects

diff --git a/.github/workflows/maven-check-deps-build-publish.yml b/.github/workflows/maven-check-deps-build-publish.yml
--- a/.github/workflows/maven-check-deps-build-publish.yml
+++ b/.github/workflows/maven-check-deps-build-publish.yml
@@ -143,44 +143,40 @@ jobs:
           echo "List of modules to check for dependency changes:"
           echo "$modules"
           
-          # Iterate over each module
-          for module in $modules; do
-            modulePath=$(echo $module | sed 's/\\/\//g')
+          moduleCount=$(wc -l <<< "$modules")
+          if [ "$moduleCount" -eq 1 ]; then
+            reportSuffix=comparison
+          else
+            reportSuffix=comparison-all
+          fi
           
-            # Navigate to the module directory
-            cd $(dirname $modulePath)
-          
-            # Get the groupId, artifactId, and version
-            groupId=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)
-            artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
-            version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-          
-            set +e
-            reportFile=./target/${artifactId}-${version}-comparison.txt
-            if [ -f $reportFile ]; then
-              comparisonResult=$(cat $reportFile)
-            
-            if [ $comparisonResult -eq 0 ]; then
-              echo "No dependency change. Exit (0)"
-            elif [ $comparisonResult -eq 1 ]; then
-              echo "One or more dependency has changed. Exit (1)"
-               # Set hasChanged to 1 (true) if a difference is found
-              hasChanged=1
-            elif [ $comparisonResult -eq -1 ]; then
-              echo "Looks like this is the first build. Exit (1)"
-              hasChanged=-1
-            else
-              echo "Unknown error occurred."
-            fi
-            else
-              echo "Local dependency report is not found at '${reportFile}'."
-              echo "Dependency changes not tracked. Exit (0)"
-            fi
-            set -e
-          
-            # Navigate back to the parent directory
-            cd -
-          done
+          # Get the groupId, artifactId, and version
+          groupId=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)
+          artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
+          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+        
+          set +e
+          reportFile=./target/${artifactId}-${version}-${reportSuffix}.txt
+          if [ -f $reportFile ]; then
+            comparisonResult=$(cat $reportFile)
+        
+          if [ "$comparisonResult" -eq 0 ]; then
+            echo "No dependency change. Exit (0)"
+          elif [ "$comparisonResult" -eq 1 ]; then
+            echo "One or more dependency has changed. Exit (1)"
+             # Set hasChanged to 1 (true) if a difference is found
+            hasChanged=1
+          elif [ "$comparisonResult" -eq -1 ]; then
+            echo "Looks like this is the first build. Exit (1)"
+            hasChanged=-1
+          else
+            echo "Unknown error occurred."
+          fi
+          else
+            echo "Local dependency report is not found at '${reportFile}'."
+            echo "Dependency changes not tracked. Exit (0)"
+          fi
+          set -e
           
           # Export hasChanged to be used in later steps of the GitHub workflow
           echo hasChanged=$hasChanged >> "$GITHUB_OUTPUT"
